using System.Collections.Generic;
using System.Data;
using System.Linq;
using YuGiOh.Showcase.Domain.Entities.Carta;

namespace YuGiOh.Showcase.Application.Services
{
    public class CartaService
    {
        private readonly List<Carta> _cartas = new List<Carta>
        {
            //new Carta(1, "nombre", TipoCarta, TipoAtributo. ,"descripcion", 1=nivelRango, Atq, Def )
            //new Carta(1, "", TipoCarta,  TipoAtributo. ,"", 1, 1, 1 )
            new Carta(1, "Conejo oscuro", TipoCarta.Dark , TipoAtributo.bestia ,"Salta arriba, abajo y por todos lados, Nadie puede ponerle la mano encima a este divertido conejo ", 4, 1100, 1500 ),
            new Carta(2, "Obelisco el atormentador archidemonio", TipoCarta.Divine ,  TipoAtributo.bestiaDivina ,"Requiere 3 Sacrificios para ser Invocado de Modo Normal (no puede ser Colocado de Modo Normal). La Invocación Normal de esta carta no puede ser negada. Cuando es Invocado de Modo Normal, no se pueden activar cartas ni efectos. Ningún jugador puede seleccionar esta carta con efectos de cartas. Una vez por turno, durante la End Phase, si esta carta fue Invocada de Modo Especial: mándala al Cementerio. Puedes Sacrificar 2 monstruos; destruye todos los monstruos que controle tu adversario. Esta carta no puede declarar un ataque en el turno en el que este efecto es activado.", 12, 4500, 4000 ),
            new Carta(3, "Mago del mandato del caos", TipoCarta.Light,  TipoAtributo.lanzadorDeConjuros ,"Niega el efecto de un monstruo que designe esta 1 carta como objetivo", 6, 2400, 1900 ),
            new Carta(4, "Conductor de armazón-PSI", TipoCarta.Light,  TipoAtributo.psiquico ,"Un soldado Psíquico que entra en batalla en contra de las Fuerzas de Seguridad sobre corrientes de rayos, usando un amplificador autonómico llamado 'Armazón-PSÍ'.", 6, 2500, 0 ),
            new Carta(5, "Anubis", TipoCarta.Divine,  TipoAtributo.bestiaDivina ,"Esta carta no puede ser Invocada de Modo Normal ni Colocada. No puede ser Invocada de Modo Especial, excepto cuando 'Esfinge Andro', 'Esfinge Teleia' y 'Theinen la Gran Esfinge' fueron destruidas en batalla y enviadas al Cementerio. Esta carta no puede ser destruida ni en batalla ni por efectos de cartas. Gana 800 ATK/DEF por cada monstruo de OSCURIDAD en el Cementerio de cualquier jugador. Si esta carta destruye un monstruo en batalla, inflige 2500 puntos de daño al adversario. Si esta carta deja el Campo, inflige 2500 puntos de daño a su dueño.", 12, 5000, 5000 ),
            new Carta(6, "Dragón blanco de ojos azules", TipoCarta.Light,  TipoAtributo.dragon ,"Este legendario dragón es una poderosa máquina de destrucción. Virtualmente invencible, muy pocos se han enfrentado a esta impresionante criatura y han vivido para contarlo.", 8, 3000, 2500 ),
            new Carta(7, "Golem de mecanismo antiguo definitivo", TipoCarta.Earth,  TipoAtributo.maquina ," 'Golem de Mecanismo Antiguo' + 2 monstruos 'Mecanismo Antiguo'Debe ser Invocado por Fusión. Si esta carta ataca a un monstruo en Posición de Defensa, inflige daño de batalla de penetración. Si esta carta ataca, hasta el final del Damage Step tu adversario no puede activar Cartas Mágicas/de Trampa. Si esta carta es destruida: puedes seleccionar 1 'Golem de Mecanismo Antiguo' en tu Cementerio; Invócalo de Modo Especial, ignorando sus condiciones de Invocación.", 10, 4400, 3400 ),
            new Carta(8, "Exodia Necross", TipoCarta.Dark, TipoAtributo.lanzadorDeConjuros ,"No puede ser Invocado de Modo Normal/Colocado. Debe ser Invocado de Modo Especial con 'Contrato con Exodia'. No puede ser destruido en batalla o por efectos de Mágicas/Trampas. Una vez por turno, durante tu Standby Phase: esta carta gana 500 ATK. Destruye esta carta a menos que todas estas 5 cartas estén en tu Cementerio - 'Exodia, el Prohibido', 'Brazo Derecho del Prohibido', 'Brazo Izquierdo del Prohibido', 'Pierna Derecha del Prohibido' y 'Pierna Izquierda del Prohibido'.", 4, 1800, 0 ),
            new Carta(9, "Zushin el gigante durmiente", TipoCarta.Earth,  TipoAtributo.guerrero , "No puede ser Invocado de Modo Normal/Colocado. Debe ser Invocado de Modo Especial (desde tu mano) Sacrificando un monstruo que controles con 10 Contadores Zushin. Una vez por turno: puedes mostrar esta carta en tu mano, y después seleccionar 1 Monstruo Normal de Nivel 1 que controles (sigue mostrando esta carta hasta el final de este turno); pon 1 Contador Zushin en ella. No es afectada por efectos de otras cartas. Si esta carta batalla con un monstruo, durante el cálculo de daño: el ATK/DEF de esta carta se convierten en iguales al ATK en este momento del monstruo con el que está batallando +1000, sólo durante ese cálculo de daño.", 10, 0, 0 ),
            new Carta(10, "DESCENDIENTE DEL DRAGÓN SOLAR", TipoCarta.Dark,  TipoAtributo.demonio ,"No puede ser Invocado de modo Normal. Puedes sacrificar un monstruo que controles; eInvoca esta carta de modo especial (de tu mano). Cuando esta carta es Invocada de Modo Especial por su propio efecto: Puedes Invocar de Modo Especial hasta 2 'Descendiente del Dragón Solar' desde tu Deck. si sacrificas esta esta carta para la Invocación de tributo de 'El dragón alado de Ra', obtiene este efecto.•No se ve afectado por los efectos de otras cartas.•Una vez por duelo: puedes Sacrificar hasta 3 monstruos que controlas esta carta gana ATK y DEF igual al ATK y DEF total de los monstruos sacrificados", 4, 1000, 1200 ),
            new Carta(11, "Snifer el dragón del cielo", TipoCarta.Divine,  TipoAtributo.bestiaDivina ,"Requiere 3 Sacrificios para ser Invocado de Modo Normal (no puede ser Colocado de Modo Normal). La Invocación Normal de esta carta no puede ser negada. Cuando es Invocado de Modo Normal, no se pueden activar cartas ni efectos. Una vez por turno, durante la End Phase, si esta carta fue Invocada de Modo Especial: mándala al Cementerio. Gana 1000 ATK/DEF por cada carta en tu mano. Si uno o más monstruos son Invocados de Modo Normal o Especial al Campo de tu adversario en Posición de Ataque: ese o esos monstruos pierden 2000 ATK y después, si su ATK quedó reducido a 0 como resultado, destrúyelos.", 10, 10000, 10000 ),
            new Carta(12, "Sabio Negro", TipoCarta.Dark,  TipoAtributo.lanzadorDeConjuros ,"No puede ser Invocado de Modo Normal, ni Colocado. Debe ser primero Invocado de Modo Especial (desde tu mano o Deck) Sacrificando 1 'Mago Oscuro' inmediatamente después de aplicar el efecto de 'Mago del Tiempo' en el que acertaste en el lanzamiento de la moneda. Cuando este monstruo es Invocado de Modo Especial de esta forma: añade a tu mano, desde tu Deck, 1 Carta Mágica.", 9, 2800, 3200 ),
            new Carta(13, "Varita del mago", TipoCarta.Dark,  TipoAtributo.lanzadorDeConjuros ,"Cuando esta carta es Invocada de Modo Normal: puedes añadir a tu mano 1 Mágica/Trampa en tu Deck que mencione 'Mago Oscuro'. Durante el turno de tu adversario, si activas una Carta Mágica/de Trampa o su efecto mientras esta carta esté en tu Cementerio (excepto durante el Damage Step): puedes Sacrificar 1 monstruo Lanzador de Conjuros; añade esta carta a tu mano. Sólo puedes usar cada efecto de 'Varita de Mago' una vez por turno.", 1, 1600, 100 )
        };
    }
}